// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEFN5bY553Ioaya4TRh4cAvsNW0uZqaR8',
    appId: '1:531048822380:web:d88c33c00dbe5a5010ca49',
    messagingSenderId: '531048822380',
    projectId: 'degreehub-f674b',
    authDomain: 'degreehub-f674b.firebaseapp.com',
    storageBucket: 'degreehub-f674b.firebasestorage.app',
    measurementId: 'G-ENQ3DFKEP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY38elddEyK6RUAzFdOReRhSZPy7POAe8',
    appId: '1:531048822380:android:7b8c32d2be22bb7410ca49',
    messagingSenderId: '531048822380',
    projectId: 'degreehub-f674b',
    storageBucket: 'degreehub-f674b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0F7pny3O7vwgRxMmLsDwnjPScqB4YhCY',
    appId: '1:531048822380:ios:0c61b489b19ca91710ca49',
    messagingSenderId: '531048822380',
    projectId: 'degreehub-f674b',
    storageBucket: 'degreehub-f674b.firebasestorage.app',
    iosClientId: '531048822380-d5879u48brt641ccd4s733hs3tvbmcu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.degreehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0F7pny3O7vwgRxMmLsDwnjPScqB4YhCY',
    appId: '1:531048822380:ios:0c61b489b19ca91710ca49',
    messagingSenderId: '531048822380',
    projectId: 'degreehub-f674b',
    storageBucket: 'degreehub-f674b.firebasestorage.app',
    iosClientId: '531048822380-d5879u48brt641ccd4s733hs3tvbmcu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.degreehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEFN5bY553Ioaya4TRh4cAvsNW0uZqaR8',
    appId: '1:531048822380:web:8b6588c904d3412910ca49',
    messagingSenderId: '531048822380',
    projectId: 'degreehub-f674b',
    authDomain: 'degreehub-f674b.firebaseapp.com',
    storageBucket: 'degreehub-f674b.firebasestorage.app',
    measurementId: 'G-ZS7VERPXFV',
  );
}
